### PR TITLE
Changed some panics to errors so the timeout checking thread won't fail

### PR DESCRIPTION
**Pull request by fhaynes**
Looks like @TimonPost already did most of it.

### CODE REVIEW

**Comment by fhaynes** [comment]
Resolves #82

**Comment by TimonPost** [comment]
How did this resolve the issue? You'd only removed panics.

**Comment by LucioFranco** [comment]
Yeah as @TimonPost says, this will just continue to spew errors because the lock will continue to be in the Poisoned state.

**Comment by fhaynes** [comment]
Closing in favor of https://github.com/amethyst/laminar/pull/101 which solves this and more in a better way.

**Pull request closed without merging**
