### PR TITLE
Change CRC32 to CRC16 in `protocol_version`.

### LINKED ISSUE #152: Switch protocol version to CRC16.
Protocol version is currently a CRC32, we could save two bytes by making it a CRC16.

I saw [this](https://forums.intel.com/s/question/0D50P00003yyG94SAE/16bit-crc-vs-32bit-crc?language=en_US)

So basically a CRC32 can cover 500MBytes and a CRC16 can cover: 8kBytes.

- Protocol version is located in the [StandardHeader](https://github.com/amethyst/laminar/blob/master/src/packet/header/standard_header.rs#L14)
- CRC32 is calculated [here](https://github.com/amethyst/laminar/blob/master/src/protocol_version.rs)

### PR DESCRIPTION
**Pull request by daxpedda**
@jstnlef you pointed out in discord some other ideas for that issue.
Still open to other ideas that we can discuss in #152.

Fixes #152.

### CODE REVIEW

**Comment by TimonPost** [comment]
Looks good! Let's wait what the CD/CI says.

**Comment by TimonPost** [comment]
Let's merge this!

**Comment by TimonPost** [comment]
bors -r=TimonPost

**Comment by daxpedda** [comment]
As far as I can see this is failing because of a test, that isn't part of the PR, not being formatted.

**Comment by jstnlef** [comment]
Why did we try to merge this? Did we reach a decision? Did I miss something?

**Comment by TimonPost** [comment]
It is at least an improvement to our current situation, I don't see the reason why it could not be merged.

**Comment by jstnlef** [comment]
I mean I guess so. Though the expectation I have is that this should be changed immediately. We need to decide what we want sooner rather than later.

**Comment by TimonPost** [comment]
After that this PR was created we came to a conclusion that we might want to take another approach on a protocol version and CRC16 implementation, I don't expect this to be ready this week. This PR does only a minor tweak and I don't see the reason not to merge it; it is an improvement on what we have right now.

**Pull request merged**
