### PR TITLE
Refactored error and removed failure

### LINKED ISSUE #69: Remove failure and revert to Error enum
Remove failure and revert back to error enums. This is mostly because failure 1.0 is being deprecated.

### PR DESCRIPTION
**Pull request by TimonPost**
Fixed #69

### CODE REVIEW

**Comment by TimonPost** [comment]
I think we can merge this directly. @LucioFranco already reviewed the error handling when I implemented the same kind of error handling for amethyst_netork. And all the changes are just renames. 


I renamed `NetworkError` to `ErrorKind`
I renamed `NetworkResult` to `Result`

**Comment by jstnlef** [comment]
Looks good 👍

**Pull request merged**
