### PR TITLE
Fix up the benchmarks so that they run

### PR DESCRIPTION
**Pull request by jstnlef**
I'm not sure that this is even wanted or needed but it was just something I noticed when digging though the code.

### CODE REVIEW

**Comment by TimonPost** [comment]
Didn't the benchmarks ran?

**Comment by jstnlef** [comment]
The benchmarks weren't running for me. It seems that some of the structs the benchmarks were using were no longer publicly available.

**Comment by TimonPost** [comment]
bord r=TimonPost

**Comment by TimonPost** [comment]
bors r=TimonPost

**Pull request merged**
