### PR TITLE
Move time access to public boundaries

### PR DESCRIPTION
**Pull request by BourgondAries**
NOTE: This series depends on the manual polling patch series, I'm not sure how else I could split these up. See https://github.com/amethyst/laminar/pull/191

Accessing `Instant::now()` from within makes this library difficult to
test, especially when testing another system together with this library
you want to be able to precisely control time.

This also prevents tests from being flaky (the test using sleep has been replaced with an exact nanosecond-granularity check).

Using the provided looping poll from socket will still use its own time
so it's backward-compatible.

Some other parts such as "throughput" still use Instant but that should
probably be swapped out for a provided time as well.

### CODE REVIEW

**Comment by BourgondAries** [comment]
I agree with the argument position. Will do.

**Comment by BourgondAries** [comment]
@jstnlef Ok, should be good now.

**Comment by jstnlef** [comment]
Looks like the windows build is broken
```
failures:


---- net::connection::tests::connection_timed_out stdout ----

thread 'net::connection::tests::connection_timed_out' panicked at 'assertion failed: `(left == right)`

  left: `0`,

 right: `10`', src\net\connection.rs:101:9

note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

**Comment by BourgondAries** [comment]
@jstnlef Unfortunately I don't use windows so I can't test this. I don't see how this can be broken on windows unless the timer resolution is less there.

**Comment by jstnlef** [comment]
That very well could be the issue... (sigh) For the fun of it, could you try to add a `Duration::from_nanos(1)` to the `now + wait`. I'm wondering if it's a boundary issue on Windows for that API.

**Comment by BourgondAries** [comment]
Adding a nanos doesn't work. Next up, a micro

**Comment by jstnlef** [comment]
Jenkins is being such a pain. I'm alright with this now 👍

**Pull request merged**
