### PR TITLE
Socket::get_port()

### PR DESCRIPTION
**Pull request by Ploppz**
Tiny PR. Not sure about the `.expect()` - is it ok? I'm not sure in what situations it would fail.

### CODE REVIEW

**Comment by BourgondAries** [comment]
Please implement a test for this.

**Comment by BourgondAries** [comment]
I think the expect is fine, here's the relevant code from std:
```
fn sockname<F>(f: F) -> io::Result<SocketAddr>
    where F: FnOnce(*mut c::sockaddr, *mut c::socklen_t) -> c_int
{
    unsafe {
        let mut storage: c::sockaddr_storage = mem::zeroed();
        let mut len = mem::size_of_val(&storage) as c::socklen_t;
        cvt(f(&mut storage as *mut _ as *mut _, &mut len))?;
        sockaddr_to_addr(&storage, len as usize)
    }
}

pub fn sockaddr_to_addr(storage: &c::sockaddr_storage,
                    len: usize) -> io::Result<SocketAddr> {
    match storage.ss_family as c_int {
        c::AF_INET => {
            assert!(len as usize >= mem::size_of::<c::sockaddr_in>());
            Ok(SocketAddr::V4(FromInner::from_inner(unsafe {
                *(storage as *const _ as *const c::sockaddr_in)
            })))
        }
        c::AF_INET6 => {
            assert!(len as usize >= mem::size_of::<c::sockaddr_in6>());
            Ok(SocketAddr::V6(FromInner::from_inner(unsafe {
                *(storage as *const _ as *const c::sockaddr_in6)
            })))
        }
        _ => {
            Err(Error::new(ErrorKind::InvalidInput, "invalid argument"))
        }
    }
}
```

Considering a UDP socket is only AF_INET or AF_INET6, this should be safe. Or the OS fails on getsockname, which is unlikely.

**Comment by jstnlef** [comment]
Pinging this

**Comment by Ploppz** [comment]
Sorry, I have been meaning to get back to this and I agree with your suggestion. I'm just quite busy now for a few more days. I will change it when I have some time.

**Comment by jstnlef** [comment]
No worries 👍

**Comment by Ploppz** [comment]
Tiny change but is this something like you imagined? Or would it be better to store the `SocketAddr` at creation (`bind`)? I mean, I'm unsure when `local_addr()` can fail. Seeing as we create `UdpSocket` with`addresses: A` where `A: ToSocketAddr`.

**Comment by jstnlef** [comment]
`self.socket.local_addr()` should do what you want :)

**Comment by Ploppz** [comment]
ah of course >_> so I'll just make that public

**Comment by jstnlef** [comment]
erm. I'd still prefer the method. That way we don't expose any of the internals of the struct.
```
pub fn local_addr(&self) -> Result<SocketAddr> {
    self.socket.local_addr()
}
```

**Comment by jstnlef** [comment]
Just needs a rebase now :)

**Comment by BourgondAries** [comment]
Nit: Add a newline before `  #[test]`

**Comment by Ploppz** [comment]
Almost forgot to say: the rebase is done.

**Pull request merged**
